INSERT INTO CATEGORY_FACTOR(NAME,BASE_PRICE) VALUES('Sport',100);
INSERT INTO CATEGORY_FACTOR(NAME,BASE_PRICE) VALUES('Starost',100);
INSERT INTO CATEGORY_FACTOR(NAME,BASE_PRICE) VALUES('Region',100);
INSERT INTO CATEGORY_FACTOR(NAME,BASE_PRICE) VALUES('Tip putovanja',100);

INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Skijanje', 1);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Planinarenje', 1);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Skok sa padobranom', 1);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Boćanje', 1);

INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Do 16', 2);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Od 16 do 60', 2);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Od 60', 2);

INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Južna Amerika', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Evropa', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Azija', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Afrika', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Australija', 3);

INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Turističko', 4);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Poslovno',4);

INSERT INTO PRICE_LIST(FROM_DATE) VALUES ('2016-6-11');

INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (1,1,170);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (2,1,150);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (3,1,240);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (4,1,120);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (5,1,120);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (6,1,160);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (7,1,180);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (8,1,170);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (9,1,140);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (10,1,150);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (11,1,180);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (12,1,155);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (13,1,150);
INSERT INTO PRICE_LIST_ITEM(FACTOR_ID,PRICE_LIST_ID,PERCENT) VALUES (14,1,130);


