INSERT INTO CATEGORY_FACTOR(NAME) VALUES('Sport');
INSERT INTO CATEGORY_FACTOR(NAME) VALUES('Starost');
INSERT INTO CATEGORY_FACTOR(NAME) VALUES('Region');

INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Skijanje', 1);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Planinarenje', 1);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Skok sa padobranom', 1);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Boćanje', 1);


INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Do 16', 2);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Od 16 do 60', 2);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Od 60', 2);

INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Južna Amerika', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Evropa', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Azija', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Afrika', 3);
INSERT INTO FACTOR(NAME, CATEGORY_ID) VALUES ('Australija', 3);
