//created on: May 9, 2017
package drools.spring.rules

import model.request.InsurancePolicyRequest;
import model.request.InsurancePolicyCalculatePriceRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.time.LocalDate;
import isok.isok.rules.Popust;

rule "Classify Item - High Range"
    when
        $i: InsurancePolicyRequest( this.duration > 2, this.amount==null)
    then
    	modify($i){
    		setAmount((long)100000);
    	}
        System.out.println("HIGH  ");
end


rule "Grupni popust ( proba, veci od 1)"
	lock-on-active true
	when 
		$i : InsurancePolicyRequest(this.persons.size > 1)
		$lista : ArrayList()
	then
		modify($lista){
			add(new Popust("na kolicinu",10));
		}
		System.out.println("10 % na kolicinu");
end


rule "Popust na datum"
	lock-on-active true
	when
		$i : InsurancePolicyRequest(this.getStartDate().isAfter(LocalDate.of(2018,2,2)))
		$lista : ArrayList()
	then
		modify($lista){
			add(new Popust("februarski popust",11));	
		}
		System.out.println("11% na februar");
end	


rule "Grupni popust2 ( proba, veci od 1)"
	lock-on-active true
	when 
		$i : InsurancePolicyCalculatePriceRequest(this.getNumberOfPersons() > 1)
		$lista : ArrayList()
	then
		modify($lista){
			add(new Popust("na kolicinu",10));
		}
		System.out.println("10 % na kolicinu");
end


rule "Popust na datum2"
	lock-on-active true
	when
		$i : InsurancePolicyCalculatePriceRequest(this.getStartDate().isAfter(LocalDate.of(2018,2,2)))
		$lista : ArrayList()
	then
		modify($lista){
			add(new Popust("februarski popust",11));	
		}
		System.out.println("11% na februar");
end	

