//created on: May 9, 2017
package drools.spring.rules

import model.request.InsurancePolicyRequest;
import java.util.ArrayList;

rule "Classify Item - High Range"
    when
        $i: InsurancePolicyRequest( this.duration > 6, this.amount==null)
    then
    	modify($i){
    		setAmount((long)100000);
    	}
        System.out.println("HIGH  ");
end


rule "Grupni popust ( proba, veci od 1)"
	lock-on-active true
	when 
		$i : InsurancePolicyRequest(this.persons.size > 1)
		$list : ArrayList()
	then
		modify($list){
			add(new Integer(10));
		}
		System.out.println("10 % na kolicinu");
end


